version: '3'
services:
  service:
    ports:
      - "8080:8080"
    build: .
  grafana:
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    links:
      - prometheus
    image: grafana/grafana
  prometheus:
    depends_on:
      - service
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus